-- Customer engagement, newsletter and privacy-conscious analytics.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','product_view','whatsapp_click','search','quote_started','quote_sent','newsletter_signup','callback_request')),
  page_path text not null default '/',
  product_slug text,
  category_id text,
  search_term text,
  metadata jsonb not null default '{}'::jsonb,
  session_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  status text not null default 'confirmed' check (status in ('confirmed','unsubscribed','suppressed')),
  consent_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  source text not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists newsletter_email_unique on public.newsletter_subscribers (lower(email));

create table if not exists public.newsletter_campaigns (
  id uuid primary key default gen_random_uuid(),
  subject text not null,
  preview_text text not null default '',
  headline text not null,
  body text not null,
  button_label text,
  button_url text,
  image_url text,
  status text not null default 'draft' check (status in ('draft','sending','sent','failed')),
  recipient_count integer not null default 0,
  sent_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_requests (
  id uuid primary key default gen_random_uuid(),
  request_type text not null check (request_type in ('quote','callback','product_help')),
  name text not null,
  phone text not null,
  email text,
  details text not null default '',
  delivery_area text,
  preferred_time text,
  items jsonb not null default '[]'::jsonb,
  status text not null default 'new' check (status in ('new','contacted','completed','closed')),
  admin_notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promotions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text not null,
  button_label text not null default 'Explore catalogue',
  button_url text not null default '/products',
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.buying_guides (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  summary text not null,
  content text not null,
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.newsletter_campaigns enable row level security;
alter table public.customer_requests enable row level security;
alter table public.promotions enable row level security;
alter table public.buying_guides enable row level security;

create policy "Visitors add analytics" on public.analytics_events for insert to anon, authenticated with check (true);
create policy "Owners read analytics" on public.analytics_events for select to authenticated using (public.is_owner());
create policy "Owners delete analytics" on public.analytics_events for delete to authenticated using (public.is_owner());

create policy "Visitors subscribe" on public.newsletter_subscribers for insert to anon, authenticated with check (status = 'confirmed');
create policy "Owners manage subscribers" on public.newsletter_subscribers for all to authenticated using (public.is_owner()) with check (public.is_owner());
create policy "Owners manage campaigns" on public.newsletter_campaigns for all to authenticated using (public.is_owner()) with check (public.is_owner());

create policy "Visitors create requests" on public.customer_requests for insert to anon, authenticated with check (status = 'new');
create policy "Owners manage requests" on public.customer_requests for all to authenticated using (public.is_owner()) with check (public.is_owner());

create policy "Public reads active promotions" on public.promotions for select to anon, authenticated using (active or public.is_owner());
create policy "Owners manage promotions" on public.promotions for all to authenticated using (public.is_owner()) with check (public.is_owner());
create policy "Public reads active guides" on public.buying_guides for select to anon, authenticated using (active or public.is_owner());
create policy "Owners manage guides" on public.buying_guides for all to authenticated using (public.is_owner()) with check (public.is_owner());

create or replace function public.subscribe_newsletter(subscriber_email text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if subscriber_email is null or subscriber_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'Please enter a valid email address.';
  end if;
  insert into newsletter_subscribers(email, status, consent_at)
  values (lower(trim(subscriber_email)), 'confirmed', now())
  on conflict (lower(email)) do update set status = 'confirmed', consent_at = now(), unsubscribed_at = null;
end; $$;
grant execute on function public.subscribe_newsletter(text) to anon, authenticated;

create or replace function public.unsubscribe_newsletter(subscriber_email text)
returns void language plpgsql security definer set search_path = public as $$
begin
  update newsletter_subscribers set status = 'unsubscribed', unsubscribed_at = now()
  where lower(email) = lower(trim(subscriber_email));
end; $$;
grant execute on function public.unsubscribe_newsletter(text) to anon, authenticated;

drop trigger if exists newsletter_subscribers_set_updated_at on public.newsletter_subscribers;
create trigger newsletter_subscribers_set_updated_at before update on public.newsletter_subscribers for each row execute function public.set_updated_at();
drop trigger if exists newsletter_campaigns_set_updated_at on public.newsletter_campaigns;
create trigger newsletter_campaigns_set_updated_at before update on public.newsletter_campaigns for each row execute function public.set_updated_at();
drop trigger if exists customer_requests_set_updated_at on public.customer_requests;
create trigger customer_requests_set_updated_at before update on public.customer_requests for each row execute function public.set_updated_at();
drop trigger if exists promotions_set_updated_at on public.promotions;
create trigger promotions_set_updated_at before update on public.promotions for each row execute function public.set_updated_at();
drop trigger if exists buying_guides_set_updated_at on public.buying_guides;
create trigger buying_guides_set_updated_at before update on public.buying_guides for each row execute function public.set_updated_at();

create index if not exists analytics_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_event_name_idx on public.analytics_events(event_name);
create index if not exists requests_created_at_idx on public.customer_requests(created_at desc);

insert into public.buying_guides(slug,title,summary,content,sort_order) values
('choose-the-right-ac','How to choose the right AC size','A practical starting point for choosing cooling capacity for your room.','Room size, sunlight, ceiling height and the number of people all affect cooling needs. Share your room dimensions with our team so we can help you compare suitable options. Always confirm the exact model, power requirements and installation needs before purchase.',1),
('inverter-vs-non-inverter','Inverter or non-inverter?','Understand the practical difference before you enquire.','Inverter appliances adjust their output instead of repeatedly running at full power. Your usage pattern, power supply and budget should guide the decision. Ask us to compare available models for your home or office.',2),
('choose-a-tv-size','Choosing a comfortable TV size','Match screen size to your room and viewing distance.','A larger screen is not automatically better for every room. Consider viewing distance, wall space, picture quality and how the television will be used. Send us your preferred size and budget range for suitable options.',3)
on conflict (slug) do nothing;

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='promotions') then alter publication supabase_realtime add table public.promotions; end if;
end $$;
